#include "NNError.h"

const NNERROR_e NNERROR[] =
{
	NNERROR_SUCCESS,
	NNERROR_INVALID_FUNCTION,
	NNERROR_FILE_NOT_FOUND,
	NNERROR_PATH_NOT_FOUND,
	NNERROR_TOO_MANY_OPEN_FILES,
	NNERROR_ACCESS_DENIED,
	NNERROR_INVALID_HANDLE,
	NNERROR_ARENA_TRASHED,
	NNERROR_NOT_ENOUGH_MEMORY,
	NNERROR_INVALID_BLOCK,
	NNERROR_BAD_ENVIRONMENT,
	NNERROR_MAX,
};

const int NNERROR_NUM[] =
{
	/*[NNERROR_SUCCESS]             = */ 0,
	/*[NNERROR_INVALID_FUNCTION]    = */ 1,
	/*[NNERROR_FILE_NOT_FOUND]      = */ 2,
	/*[NNERROR_PATH_NOT_FOUND]      = */ 3,
	/*[NNERROR_TOO_MANY_OPEN_FILES] = */ 4,
	/*[NNERROR_ACCESS_DENIED]       = */ 5,
	/*[NNERROR_INVALID_HANDLE]      = */ 6,
	/*[NNERROR_ARENA_TRASHED]       = */ 7,
	/*[NNERROR_NOT_ENOUGH_MEMORY]   = */ 8,
	/*[NNERROR_INVALID_BLOCK]       = */ 9,
	/*[NNERROR_BAD_ENVIRONMENT]     = */ 10,
};

const char * NNERROR_STR[] =
{
	/*[NNERROR_SUCCESS]             = */ "NNERROR_SUCCESS",
	/*[NNERROR_INVALID_FUNCTION]    = */ "NNERROR_INVALID_FUNCTION",
	/*[NNERROR_FILE_NOT_FOUND]      = */ "NNERROR_FILE_NOT_FOUND",
	/*[NNERROR_PATH_NOT_FOUND]      = */ "NNERROR_PATH_NOT_FOUND",
	/*[NNERROR_TOO_MANY_OPEN_FILES] = */ "NNERROR_TOO_MANY_OPEN_FILES",
	/*[NNERROR_ACCESS_DENIED]       = */ "NNERROR_ACCESS_DENIED",
	/*[NNERROR_INVALID_HANDLE]      = */ "NNERROR_INVALID_HANDLE",
	/*[NNERROR_ARENA_TRASHED]       = */ "NNERROR_ARENA_TRASHED",
	/*[NNERROR_NOT_ENOUGH_MEMORY]   = */ "NNERROR_NOT_ENOUGH_MEMORY",
	/*[NNERROR_INVALID_BLOCK]       = */ "NNERROR_INVALID_BLOCK",
	/*[NNERROR_BAD_ENVIRONMENT]     = */ "NNERROR_BAD_ENVIRONMENT",
};